apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  namespace: default  # Change this to your actual namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
  volumeMode: Filesystem
  storageClassName: mysqlstorageclass

