apiVersion: v1
kind: Service
metadata: 
  name: mysqlnp
spec:
  type: NodePort
  selector:
    app: mysql
    version: "8.0.37"
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31000
  