apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysqlpv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqlstorageclass
  hostPath:
    path: /u01/data